Added version consistency check before each build
NASAWorldWind/WebWorldWind pull request #896
Opened 2023-10-24 21:37 UTC by Beak-man

### Description of the Change
Additionally to the version number located in package.json which provides us with versioning for the npm package, we internally store a VERSION property in the main WorldWind object. Since the latter predated the publishing of the npm package and due requiring manual updating, it has not been in sync with the package.json value.

- This change adds a script that verifies consistency between these two values before performing a build, canceling the build if the check fails. 
- The value in WorldWind.js is updated to reflect the numbering as found in the npm package and GitHub's releases.

Tested regex in line 23 of the script at https://regex101.com/. I also tested an assortment of version numbers and nonsensical strings.

### Why Should This Be In Core?
It provides the developer the means to ensure that version numbers are consistent across the project without incurring in breaking changes to the WorldWind object.

### Benefits
Simple way to maintain version consistency between the two files where the value is stored.

### Potential Drawbacks
For future releases, It still requires manually updating the version number in WorldWind.VERSION. Since automatically rewriting it with each build could be considered an antipattern, manual updating is deemed acceptable.

2023-10-24 21:55 UTC, ApacheAde commented
Version

2023-10-24 21:56 UTC, ApacheAde requested changes
![DALL·E 2023-10-24 21 17 08 - Re imagine the Friends TVs show cast as snoopy peanuts characters](https://github.com/NASAWorldWind/WebWorldWind/assets/45696323/4850aa16-f0a0-40c9-8357-71f2e6a72589)

2024-01-18 18:08 UTC, markpet49 requested changes
I can't find any evidence that versioncheck.js gets executed with the build command 'npm run build'. How does versioncheck get initiated?

2024-01-25 20:34 UTC, PJHogan approved these changes

2024-02-15 20:03 UTC, markpet49 approved these changes
Looks good.

2024-02-27 17:43 UTC, merged